iiwa_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Rev41
    - Rev42
    - Rev43
    - Rev44
    - Rev45
    - Rev46
    - Rev47
  gains:
    Rev41:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev42:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev43:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev44:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev45:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev46:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev47:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
kmp_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - virtual_joint
  gains:
    virtual_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Slider26
    - Slider27
  gains:
    Slider26:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Slider27:
      p: 100
      d: 1
      i: 1
      i_clamp: 1