controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - Slider26
      - Slider27
initial:  # Define initial robot poses per group
  - group: gripper
    pose: rest