gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Slider26
    - Slider27
  gains:
    Slider26:
      p: 10000
      d: 1
      i: 10
      i_clamp: 1
    Slider27:
      p: 10000
      d: 1
      i: 10
      i_clamp: 1