controller_list:
  - name: fake_gripkit_cr_plus_l_bb_controller
    type: $(arg fake_execution_type)
    joints:
      - Slider26
      - Slider27
initial:  # Define initial robot poses per group
  - group: gripkit_cr_plus_l_bb
    pose: rest