controller_list:
  - name: fake_iiwa_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev44
      - Rev45
      - Rev46
      - Rev47
      - Rev48
      - Rev49
      - Rev50
initial:  # Define initial robot poses per group
  - group: iiwa
    pose: rest