iiwa_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev44
    - Rev45
    - Rev46
    - Rev47
    - Rev48
    - Rev49
    - Rev50
  gains:
    Rev44:
      p: 10000
      d: 50
      i: 10
      i_clamp: 1
    Rev45:
      p: 50000
      d: 50
      i: 10
      i_clamp: 1
    Rev46:
      p: 50000
      d: 50
      i: 10
      i_clamp: 1
    Rev47:
      p: 50000
      d: 50
      i: 10
      i_clamp: 1
    Rev48:
      p: 2000
      d: 20
      i: 10
      i_clamp: 1
    Rev49:
      p: 1000
      d: 10
      i: 1
      i_clamp: 1
    Rev50:
      p: 1000
      d: 10
      i: 1
      i_clamp: 1