iiwa_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Rev39
    - Rev40
    - Rev41
    - Rev42
    - Rev43
    - Rev44
    - Rev45
  gains:
    Rev39:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev40:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev41:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev42:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev43:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev44:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev45:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Slider26
    - Slider27
  gains:
    Slider26:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Slider27:
      p: 100
      d: 1
      i: 1
      i_clamp: 1