controller_list:
  - name: iiwa_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Rev39
      - Rev40
      - Rev41
      - Rev42
      - Rev43
      - Rev44
      - Rev45
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Slider26
      - Slider27