controller_list:
  - name: fake_iiwa7_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev25
      - Rev26
      - Rev27
      - Rev28
      - Rev29
      - Rev30
      - Rev31
  - name: fake_kmp200_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
initial:  # Define initial robot poses per group
  - group: iiwa7
    pose: rest