iiwa_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Rev25
    - Rev26
    - Rev27
    - Rev28
    - Rev29
    - Rev30
    - Rev31
  gains:
    Rev25:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev26:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev27:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev28:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev29:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev30:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev31:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
kmp_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - virtual_joint
  gains:
    virtual_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1