iiwa_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev44
    - Rev45
    - Rev46
    - Rev47
    - Rev48
    - Rev49
    - Rev50
  gains:
    Rev44:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    Rev45:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    Rev46:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    Rev47:
      p: 200
      d: 20
      i: 10
      i_clamp: 100
    Rev48:
      p: 100
      d: 10
      i: 0.1
      i_clamp: 100
    Rev49:
      p: 50
      d: 5
      i: 0.1
      i_clamp: 100
    Rev50:
      p: 10
      d: 1
      i: 0.1
      i_clamp: 100
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Slider26
    - Slider27
  gains:
    Slider26:
      p: 10000
      d: 1
      i: 10
      i_clamp: 1
    Slider27:
      p: 10000
      d: 1
      i: 10
      i_clamp: 1