controller_list:
  - name: fake_iiwa7_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev45
      - Rev46
      - Rev47
      - Rev48
      - Rev49
      - Rev50
      - Rev51
  - name: fake_gripkit_cr_plus_l_cc_controller
    type: $(arg fake_execution_type)
    joints:
      - Slider26
      - Slider27
initial:  # Define initial robot poses per group
  - group: iiwa7
    pose: rest
  - group: gripkit_cr_plus_l_cc
    pose: rest