iiwa_Effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev01
    - Rev02
    - Rev03
    - Rev04
    - Rev05
    - Rev06
    - Rev07
  constraints:
    Rev01: 
      goal: &goal_pos_constraint 0.001
    Rev02: 
      goal: *goal_pos_constraint
    Rev03: 
      goal: *goal_pos_constraint
    Rev04:
      goal: *goal_pos_constraint
    Rev05:
      goal: *goal_pos_constraint
    Rev06: 
      goal: *goal_pos_constraint
    Rev07:
      goal: *goal_pos_constraint
  gains:
    Rev01: {p: 1000, i: 40, d: 20, i_clamp: 100}
    Rev02: {p: 9000, i: 1500, d: 50, i_clamp: 2000}
    Rev03: {p: 1000, i: 40, d: 20, i_clamp: 100}
    Rev04: {p: 2500, i: 100, d: 30, i_clamp: 150}
    Rev05: {p: 250, i: 30, d: 20, i_clamp: 100}
    Rev06: {p: 800, i: 50, d: 15, i_clamp: 100}
    Rev07: {p: 100, i: 5, d: 1, i_clamp: 100}
gripper_Effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Slider01
    - Slider02
  gains:
    Slider01: {p: 5000, i: 10, d: 1, i_clamp: 1}
    Slider02: {p: 5000, i: 10, d: 1, i_clamp: 1}
iiwa_Position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Rev01
    - Rev02
    - Rev03
    - Rev04
    - Rev05
    - Rev06
    - Rev07
  constraints:
    Rev01: 
      goal: *goal_pos_constraint
    Rev02: 
      goal: *goal_pos_constraint
    Rev03: 
      goal: *goal_pos_constraint
    Rev04:
      goal: *goal_pos_constraint
    Rev05:
      goal: *goal_pos_constraint
    Rev06: 
      goal: *goal_pos_constraint
    Rev07:
      goal: *goal_pos_constraint
  gains:
    Rev01: {p: 1000, i: 40, d: 30, i_clamp: 100}
    Rev02: {p: 5000, i: 150, d: 30, i_clamp: 300}
    Rev03: {p: 1000, i: 40, d: 30, i_clamp: 100}
    Rev04: {p: 2500, i: 100, d: 30, i_clamp: 150}
    Rev05: {p: 250, i: 30, d: 20, i_clamp: 100}
    Rev06: {p: 800, i: 50, d: 15, i_clamp: 100}
    Rev07: {p: 100, i: 5, d: 1, i_clamp: 100}
gripper_Position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Slider01
    - Slider02
  gains:
    Slider01: {p: 5000, i: 10, d: 1, i_clamp: 1}
    Slider02: {p: 5000, i: 10, d: 1, i_clamp: 1}
iiwa_Velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - Rev01
    - Rev02
    - Rev03
    - Rev04
    - Rev05
    - Rev06
    - Rev07
  constraints:
    Rev01: 
      goal: *goal_pos_constraint
    Rev02: 
      goal: *goal_pos_constraint
    Rev03: 
      goal: *goal_pos_constraint
    Rev04:
      goal: *goal_pos_constraint
    Rev05:
      goal: *goal_pos_constraint
    Rev06: 
      goal: *goal_pos_constraint
    Rev07:
      goal: *goal_pos_constraint
  gains:
    Rev01: {p: 1000, i: 40, d: 30, i_clamp: 100}
    Rev02: {p: 5000, i: 150, d: 30, i_clamp: 300}
    Rev03: {p: 1000, i: 40, d: 30, i_clamp: 100}
    Rev04: {p: 2500, i: 100, d: 30, i_clamp: 150}
    Rev05: {p: 250, i: 30, d: 20, i_clamp: 100}
    Rev06: {p: 800, i: 50, d: 15, i_clamp: 100}
    Rev07: {p: 100, i: 5, d: 1, i_clamp: 100}
gripper_Velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - Slider01
    - Slider02
  gains:
    Slider01: {p: 5000, i: 10, d: 1, i_clamp: 1}
    Slider02: {p: 5000, i: 10, d: 1, i_clamp: 1}
# Provide random PID gains to gazebo_ros_control 
# to suppress ERROR when using position_controllers and velocity_controllers
gazebo_ros_control:
  pid_gains:
    Rev01: {p: 1000, i: 40, d: 30, i_clamp: 100}
    Rev02: {p: 5000, i: 150, d: 30, i_clamp: 300}
    Rev03: {p: 1000, i: 40, d: 30, i_clamp: 100}
    Rev04: {p: 2500, i: 100, d: 30, i_clamp: 150}
    Rev05: {p: 250, i: 30, d: 20, i_clamp: 100}
    Rev06: {p: 800, i: 50, d: 15, i_clamp: 100}
    Rev07: {p: 100, i: 5, d: 1, i_clamp: 100}
