controller_list:
  - name: fake_kmp200_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
initial:  # Define initial robot poses per group
#  - group: kmp200
#    pose: home

  []