gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Slider26
    - Slider27
  gains:
    Slider26:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Slider27:
      p: 100
      d: 1
      i: 1
      i_clamp: 1